defaults:
    - tdmpc2
    - _self_

# environment
seed: 40
task: stack-cube-semi
obs: state
num_envs: 16

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 4_000_000
batch_size: 256
steps_per_update: 4 # utd = steps_per_update / num_envs (in this implementation)
buffer_size: 1_000_000
exp_name: default
save_freq: 500_000
oversample_ratio: 0.5
policy_pretraining: true
use_demos: ???

# pretraining
pretrain:
    n_epochs: 10000
    eval_freq: 4000
    log_freq: 500

# logging
wandb_project: maniskill3
wandb_entity: alopez
wandb_silent: true
disable_wandb: true
save_csv: false

# drS
drS_enable: true
n_stages: ???
demo_path: /home/adria/tdmpc2/demo_data/ManiSkill3/state/TDMPC/StackCube_200.pkl
drS_discriminator:
    disc_lr: 3e-4
    batch_size: 256

# misc, no effect, just for logging grouping purposes
tag: debugging
n_demos: 25
