defaults:
    - tdmpc2
    - _self_

# environment
task: stack-cube-semi
obs: state

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
buffer_size: 1_000_000
exp_name: default

# logging
wandb_project: tdmpc2-drS-learning
wandb_entity: alopez
wandb_silent: true
disable_wandb: false
save_csv: false

# drS
demo_path: /home/adria/tdmpc2/demo_data/StackCube_200.pkl
drS_discriminator:
    disc_lr: 3e-4
    batch_size: 256
    buffer_size: 10_000_000
