defaults:
    - tdmpc2
    - _self_

# environment
task: stack-cube-semi
obs: state
num_envs: 16

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
steps_per_update: 4
buffer_size: 1_000_000
exp_name: default
save_freq: 500_000

# logging
wandb_project: tdmpc2-drS-learning
wandb_entity: alopez
wandb_silent: true
disable_wandb: false
save_csv: false

# drS
demo_path: ???
drS_discriminator:
    disc_lr: 3e-4
    batch_size: 256
    buffer_size: 10_000_000

drs_input: ??? # no effect, just for logging purposes
