defaults:
    - tdmpc2
    - _self_

# environment
task: pick-place-semi
obs: state
num_envs: 16

# evaluation
checkpoint: ???
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
steps_per_update: 4 # utd = steps_per_update / num_envs (in this implementation)
buffer_size: 1_000_000
exp_name: default
save_freq: 500_000
oversample_ratio: 0.5
policy_pretraining: true
use_demos: ???

# logging
wandb_project: tdmpc2-drS-learning
wandb_entity: alopez
wandb_silent: true
disable_wandb: false
save_csv: false

# drS
drS_enable: false
demo_path: /home/adria/tdmpc2/demo_data/TDMPC/PickAndPlace_100.pkl
prefill_buffer_with_demos: true
drS_discriminator:
    disc_lr: 3e-4
    batch_size: 256
    buffer_size: 10_000_000

# misc, no effect, just for logging grouping purposes
tag: ???
n_demos: ???
