defaults:
    - tdmpc2
    - _self_

# environment
task: pick-place-semi
obs: state
save_obs: rgbd
num_envs: 16

# evaluation
checkpoint: /home/adria/tdmpc2/ckpt/tdmpc/PickCube.pt
eval_episodes: 100

# saving
save_trajectory: true
success_only: true
log_path: .
save_video: true

# misc
multitask: false

# rendering
render_for_obs: false
