defaults:
    - tdmpc2
    - _self_

# environment
task: peg-insertion-semi
obs: state
num_envs: 16

# evaluation
checkpoint: /home/adria/tdmpc2/ckpt/tdmpc/PegInsertionSide.pt
eval_episodes: 100

# saving
save_trajectory: true
success_only: true
log_path: .
save_video: true

# misc
multitask: false

# rendering
render_for_obs: true
