defaults:
    - tdmpc2
    - _self_

# environment
task: ms-peg-insertion-semi
obs: rgbd
obs_save: rgbd
num_envs: 1
sim_backend: gpu

# evaluation
checkpoint: /home/adria/tdmpc2/ckpt/Maniskill3/DEMO3/PegInsertionSide/agent_1000000.pt
disc_checkpoint: /home/adria/tdmpc2/ckpt/Maniskill3/DEMO3/PegInsertionSide/disc_1000000.pt
eval_episodes: 20
# saving
save_trajectory: false
success_only: true
log_path: .
save_video: true

# misc
render_obs: false
compile: false
add_text: false

discriminator:
    disc_lr: 3e-4
    batch_size: 256
