defaults:
    - tdmpc2
    - _self_

# environment
task: ms-peg-insertion-semi
obs: state
obs_save: rgbd
num_envs: 1
sim_backend: gpu

# evaluation
checkpoint: /home/adria/tdmpc2/ckpt/Maniskill3/tdmpc/PegInsertionSide.pt
eval_episodes: 25

# saving
save_trajectory: true
success_only: true
log_path: .
save_video: true

# misc
render_obs: true
compile: false
